Member:
  log_num_visits: false
  log_last_visited: false
Page:
  extensions:
    - DivisionPage
    - WidgetPageExtension
    - OpenGraphExtension
Page_Controller:
  extensions:
    - DivisionPage_Controller
BlogPost:
  extensions:
    - BlogFieldExtension
SiteConfig:
  extensions:
    - SiteConfigExtension
HomePageFeature:
  extensions:
    - Versioned("Stage","Live")
HomePageHeroFeature:
  extensions:
    - Versioned("Stage","Live") 
ContentBlock:
  extensions:
    - ContentBlockExtension
BlogCategory:
  extensions:
    - BlogCategoryExtension
Image:
  extensions:
    - DivisionImageExtension
LeftAndMain:
  extra_requirements_css:
    - division-project/css/cms.css
SSViewer:
  theme: division-subtheme
Page_Controller:
  extensions:
    - FlickrShortcodeControllerExtension