Controller:
  extensions:
    - SS_MinifiedResponseExtension
Page:
  extensions:
    - DivisionPage
    - WidgetPageExtension
Page_Controller:
  extensions:
    - DivisionPage_Controller
BlogPost:
  extensions:
    - BlogFieldExtension
SiteConfig:
  extensions:
    - SiteConfigExtension
HomePageFeature:
  extensions:
    - Versioned("Stage","Live")
HomePageHeroFeature:
  extensions:
    - Versioned("Stage","Live")