SiteTree:
  extensions:
    - DivisionPage
    - PublishableSiteTree
    - SiteTreePublishingEngine
    - FilesystemPublisher('cache', 'html')
Controller:
  extensions:
    - SS_MinifiedResponseExtension