---
Name: division-config
After:
    - '*'
---
SilverStripe\Security\Member:
  log_num_visits: false
  log_last_visited: false
SSViewer:
  theme: 'division-subtheme'
GDBackend:
  default_quality: 90
  